Updated description GSD-2022-1002526
cloudsecurityalliance/gsd-database pull request #2357
Opened 2022-06-29 02:33 UTC by kurtseifried

2022-07-01 17:48 UTC, joshbuker requested changes

2022-07-01 17:48 UTC, joshbuker commented on 2022/1002xxx/GSD-2022-1002526.json
> +    }
It would be good to add some sort of "This moved" identifier long term. This probably is good enough for now though.

2022-07-01 17:48 UTC, joshbuker commented on 2022/1002xxx/GSD-2022-1002526.json
> +    "GSD": {
Please re-add the original ID (GSD-2022-1002526).

2022-07-01 18:34 UTC, kurtseifried commented on 2022/1002xxx/GSD-2022-1002526.json
> +    "GSD": {
but it's not that gsd id anymore. it's the new one.

2022-07-01 22:32 UTC, joshbuker requested changes

2022-07-01 22:32 UTC, joshbuker commented on 2022/1002xxx/GSD-2022-1002526.json
> +    "GSD": {
There is no indication within the file that this is GSD-2022-1002526, and that it has been deprecated in favor of GSD-2022-2274.

This is GSD-2022-1002526, and it is essentially a redirect to GSD-2022-2274. We can't have IDs that don't specify their UID. That breaks everything.

2022-07-04 19:09 UTC, joshbuker approved these changes

2022-07-05 04:39 UTC, raphaelahrens commented on 2022/1002xxx/GSD-2022-1002526.json
> +    "GSD": {
It would be good to have a sentence in the description, to preserve the history for people who do not have the repository at hand.

2022-07-05 04:50 UTC, raphaelahrens commented on 2022/1002xxx/GSD-2022-1002526.json
> +    }
If such an identifier would be added in the form of a state, it could be used as well for identifying test data. https://github.com/cloudsecurityalliance/gsd-tools/issues/32

2022-07-05 18:05 UTC, merged